version: '3'
services:
    mysql_master:
      image: mysql:8.0.34
      container_name: mysql_master
      environment:
        MYSQL_ROOT_PASSWORD: admin
      ports:
        - "3306:3306"
      volumes:
        - "./master_conf_file:/etc/mysql/conf.d"
        - "./master_data:/var/lib/mysql:rw"
    
    mysql_slave1:
      image: mysql:8.0.34
      container_name: mysql_slave1
      environment:
        MYSQL_ROOT_PASSWORD: admin
      ports:
        - "3307:3306"
      volumes:
        - "./slave1_conf_file:/etc/mysql/conf.d"
        - "./slave1_data:/var/lib/mysql:rw"

    mysql_slave2:
      image: mysql:8.0.34
      container_name: mysql_slave2
      environment:
        MYSQL_ROOT_PASSWORD: admin
      ports:
        - "3308:3306"
      volumes:
        - "./slave2_conf_file:/etc/mysql/conf.d"
        - "./slave2_data:/var/lib/mysql:rw"

      

